use crate::world::tile::terrain::{BaseTerrain, TerrainConfig};

pub fn generate_default_terrain_set() -> Vec<TerrainConfig> {
    [
        TerrainConfig::new("DeepWater".to_string(), BaseTerrain::DeepWater, true, None),
        TerrainConfig::new(
            "ShallowWater".to_string(),
            BaseTerrain::ShallowWater,
            true,
            None,
        ),
        TerrainConfig::new_color(
            "SwampWater".to_string(),
            BaseTerrain::ShallowWater,
            true,
            (215, 240, 200),
            None,
        ),
        TerrainConfig::new("Grass".to_string(), BaseTerrain::Grass, true, None),
        TerrainConfig::new_color(
            "TundraGrass".to_string(),
            BaseTerrain::Grass,
            true,
            (230, 230, 255),
            None,
        ),
        TerrainConfig::new_color(
            "FrozenGrass".to_string(),
            BaseTerrain::Grass,
            true,
            (170, 190, 255),
            None,
        ),
        TerrainConfig::new_color(
            "PlainsGrass".to_string(),
            BaseTerrain::Grass,
            true,
            (250, 235, 220),
            None,
        ),
        TerrainConfig::new_color(
            "DarkGrass".to_string(),
            BaseTerrain::Grass,
            true,
            (225, 225, 225),
            None,
        ),
        TerrainConfig::new_color(
            "SwampGrass".to_string(),
            BaseTerrain::Grass,
            true,
            (190, 185, 160),
            None,
        ),
        TerrainConfig::new("Mud".to_string(), BaseTerrain::Mud, true, None),
        TerrainConfig::new_color(
            "Clay".to_string(),
            BaseTerrain::Mud,
            true,
            (255, 235, 220),
            None,
        ),
        TerrainConfig::new_color(
            "DarkMud".to_string(),
            BaseTerrain::Mud,
            true,
            (225, 225, 225),
            None,
        ),
        TerrainConfig::new("Sand".to_string(), BaseTerrain::Sand, true, None),
        TerrainConfig::new_color(
            "WetSand".to_string(),
            BaseTerrain::Sand,
            true,
            (235, 235, 235),
            None,
        ),
        TerrainConfig::new("Stone".to_string(), BaseTerrain::Stone, true, None),
        TerrainConfig::new_color(
            "RedStone".to_string(),
            BaseTerrain::Stone,
            true,
            (235, 200, 160),
            None,
        ),
        TerrainConfig::new_color(
            "DarkStone".to_string(),
            BaseTerrain::Stone,
            true,
            (215, 215, 215),
            None,
        ),
        TerrainConfig::new_color(
            "SandStone".to_string(),
            BaseTerrain::Stone,
            true,
            (255, 225, 175),
            None,
        ),
        TerrainConfig::new("Snow".to_string(), BaseTerrain::Snow, true, None),
        TerrainConfig::new_color(
            "BlueSnow".to_string(),
            BaseTerrain::Snow,
            false,
            (230, 240, 255),
            None,
        ),
    ]
    .to_vec()
}
